namespace Doka.EntityFrameworkCore.MySql;

/// <summary>
/// Contains the complete command sequence generated by one custom
/// migration-operation handler.
/// </summary>
public sealed class MySqlMigrationOperationResult
{
    private static readonly Regex s_outcomeCodePattern = new(
        "^[a-z][a-z0-9_]{0,63}$",
        RegexOptions.CultureInvariant | RegexOptions.NonBacktracking);

    private MySqlMigrationOperationResult(
        IReadOnlyList<MySqlMigrationCommandSpec> commands,
        string outcomeCode
    )
    {
        Commands = commands;
        OutcomeCode = outcomeCode;
    }

    /// <summary>
    /// Gets the immutable, ordered command sequence.
    /// </summary>
    public IReadOnlyList<MySqlMigrationCommandSpec> Commands { get; }

    /// <summary>
    /// Gets the stable, low-cardinality outcome code emitted by provider
    /// diagnostics.
    /// </summary>
    public string OutcomeCode { get; }

    /// <summary>
    /// Creates a generated result and snapshots its command sequence.
    /// </summary>
    /// <param name="commands">One or more validated commands.</param>
    /// <param name="outcomeCode">
    /// A stable code matching <c>^[a-z][a-z0-9_]{0,63}$</c>. Do not include SQL,
    /// object names, identifiers, or other unbounded values.
    /// </param>
    /// <returns>The immutable generated result.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="outcomeCode"/> does not satisfy the bounded contract.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// <paramref name="commands"/> is empty or contains a <see langword="null"/>
    /// element.
    /// </exception>
    public static MySqlMigrationOperationResult Generated(
        IEnumerable<MySqlMigrationCommandSpec> commands,
        string outcomeCode
    )
    {
        ArgumentNullException.ThrowIfNull(commands);
        ArgumentException.ThrowIfNullOrWhiteSpace(outcomeCode);

        if (!IsValidOutcomeCode(outcomeCode))
        {
            throw new ArgumentException(
                "The outcome code must match ^[a-z][a-z0-9_]{0,63}$.",
                nameof(outcomeCode));
        }

        var snapshot = commands.ToArray();

        if (snapshot.Length == 0 || snapshot.Any(command => command is null))
        {
            throw new ArgumentException(
                "A generated result must contain at least one non-null command.",
                nameof(commands));
        }

        return new MySqlMigrationOperationResult(Array.AsReadOnly(snapshot), outcomeCode);
    }

    internal static bool IsValidOutcomeCode(string outcomeCode)
        => s_outcomeCodePattern.IsMatch(outcomeCode);
}
