// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Doka.EntityFrameworkCore.MySql.RuntimeSmoke.CompiledModels.Basic
{
    public partial class BasicSmokeContextModel
    {
        private BasicSmokeContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("a9e78213-0665-41fd-94f7-84f9dc2c2fca"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var basicSmokeEntity = BasicSmokeEntityEntityType.Create(this);

            BasicSmokeEntityEntityType.CreateAnnotations(basicSmokeEntity);

            AddAnnotation("ProductVersion", "10.0.4");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var basicSmokeEntity = FindEntityType("Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+BasicSmokeEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            basicSmokeEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityTableBase = new TableBase("Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+BasicSmokeEntity", null, relationalModel);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "int", dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityTableBase);
            dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityTableBase.Columns.Add("Id", idColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "longtext", dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityTableBase);
            dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityTableBase.Columns.Add("Name", nameColumnBase);
            relationalModel.DefaultTables.Add("Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+BasicSmokeEntity", dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityTableBase);
            var dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityMappingBase = new TableMappingBase<ColumnMappingBase>(basicSmokeEntity, dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityTableBase, null);
            dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityTableBase.AddTypeMapping(dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityMappingBase, false);
            defaultTableMappings.Add(dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, basicSmokeEntity.FindProperty("Id")!, dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, basicSmokeEntity.FindProperty("Name")!, dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramBasicSmokeEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            basicSmokeEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var basicEntitiesTable = new Table("BasicEntities", null, relationalModel);
            var idColumn = new Column("Id", "int", basicEntitiesTable);
            basicEntitiesTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            idColumn.AddAnnotation("Doka:MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.AutoIncrement);
            var nameColumn = new Column("Name", "longtext", basicEntitiesTable);
            basicEntitiesTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            relationalModel.Tables.Add(("BasicEntities", null), basicEntitiesTable);
            var basicEntitiesTableMapping = new TableMapping(basicSmokeEntity, basicEntitiesTable, null);
            basicEntitiesTable.AddTypeMapping(basicEntitiesTableMapping, false);
            tableMappings.Add(basicEntitiesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, basicSmokeEntity.FindProperty("Id")!, basicEntitiesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, basicSmokeEntity.FindProperty("Name")!, basicEntitiesTableMapping);
            var pK_BasicEntities = new UniqueConstraint("PK_BasicEntities", basicEntitiesTable, new[] { idColumn });
            basicEntitiesTable.PrimaryKey = pK_BasicEntities;
            pK_BasicEntities.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_BasicEntities));
            var pK_BasicEntitiesKey = RelationalModel.GetKey(this,
                "Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+BasicSmokeEntity",
                new[] { "Id" });
            pK_BasicEntities.MappedKeys.Add(pK_BasicEntitiesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_BasicEntitiesKey).Add(pK_BasicEntities);
            basicEntitiesTable.UniqueConstraints.Add("PK_BasicEntities", pK_BasicEntities);
            return relationalModel.MakeReadOnly();
        }
    }
}
