// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Doka.EntityFrameworkCore.MySql.RuntimeSmoke.CompiledModels.Basic
{
    public static class BasicSmokeEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(Program.BasicSmokeEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(Program.BasicSmokeEntity @this);
    }
}
