<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doka.EntityFrameworkCore.MySql.SpecificationAdapters</AssemblyName>
    <RootNamespace>Doka.EntityFrameworkCore.MySql.SpecificationAdapters</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational.Specification.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Doka.EntityFrameworkCore.MySql/Doka.EntityFrameworkCore.MySql.csproj" />
  </ItemGroup>
</Project>
