namespace Doka.EntityFrameworkCore.MySql.IntegrationTests;

/// <summary>
/// Serializes tests that own isolated TLS-enabled database containers.
/// </summary>
[CollectionDefinition(Name, DisableParallelization = true)]
public sealed class TlsDatabaseTestGroup : ICollectionFixture<TlsDatabaseFixture>
{
    /// <summary>
    /// Gets the xUnit collection name used by TLS contract tests.
    /// </summary>
    public const string Name = "tls-integration-database";
}

/// <summary>
/// Owns isolated database containers whose server and client certificates are
/// generated by the test run rather than inherited from a developer machine.
/// </summary>
public sealed class TlsDatabaseFixture : IAsyncLifetime
{
    private TestDatabaseSession? _session;

    public async Task InitializeAsync()
    {
        var requests = IntegrationTestEnvironment
            .GetSelectedTargets()
            .Select(CreateTlsRequest)
            .ToArray();

        _session = await TestDatabaseSession
            .StartAsync(requests, evidenceScope: "tls")
            .ConfigureAwait(false);
    }

    public async Task DisposeAsync()
    {
        if (_session is null)
        {
            return;
        }

        var session = _session;
        _session = null;

        await session
            .DisposeAsync()
            .ConfigureAwait(false);
    }

    internal TestDatabaseEndpoint GetEndpoint(
        IntegrationDatabaseTarget target
    )
    {
        return (_session ?? throw new InvalidOperationException("The TLS database fixture has not initialized."))
            .GetEndpoint(
                CreateTlsRequest(target)
                    .TargetId);
    }

    private static TestDatabaseRequest CreateTlsRequest(
        IntegrationDatabaseTarget target
    )
    {
        var request = IntegrationTestEnvironment.CreateRequest(target);

        return request with
        {
            ConnectionStringEnvironmentVariable = $"{request.ConnectionStringEnvironmentVariable}_TLS",
            SecurityProfile = TestDatabaseSecurityProfile.TlsRequired,
        };
    }
}
