// <auto-generated />
using Doka.EntityFrameworkCore.MySql;
using Doka.EntityFrameworkCore.MySql.Examples.MigrationsWorkflow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doka.EntityFrameworkCore.MySql.Examples.MigrationsWorkflow.Migrations
{
    [DbContext(typeof(MigrationWorkflowContext))]
    [Migration("20260820121000_UpdateTemporalDefaults")]
    partial class UpdateTemporalDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Doka.EntityFrameworkCore.MySql.Examples.MigrationsWorkflow.MigrationWorkflowItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMySqlValueGenerationStrategy(MySqlValueGenerationStrategy.AutoIncrement);

                    b.Property<DateOnly>("EffectiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateOnly(2028, 2, 3));

                    b.Property<TimeOnly>("EffectiveTime")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("time(6)")
                        .HasDefaultValue(new TimeOnly(4, 5, 6, 654, 321));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasMySqlValueGenerationStrategy(MySqlValueGenerationStrategy.None);

                    b.HasKey("Id");

                    b.ToTable("MigrationWorkflowItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EffectiveDate = new DateOnly(2026, 8, 17),
                            EffectiveTime = new TimeOnly(12, 34, 56, 123, 456),
                            Name = "migration-safety-readback"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
