// <auto-generated />
using Doka.EntityFrameworkCore.MySql;
using Doka.EntityFrameworkCore.MySql.Examples.MigrationsWorkflow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doka.EntityFrameworkCore.MySql.Examples.MigrationsWorkflow.Migrations
{
    [DbContext(typeof(MigrationWorkflowContext))]
    partial class MigrationWorkflowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Doka.EntityFrameworkCore.MySql.Examples.MigrationsWorkflow.MigrationWorkflowItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMySqlValueGenerationStrategy(MySqlValueGenerationStrategy.AutoIncrement);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasMySqlValueGenerationStrategy(MySqlValueGenerationStrategy.None);

                    b.HasKey("Id");

                    b.ToTable("MigrationWorkflowItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "migration-safety-readback"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
