// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;
using NetTopologySuite.Geometries;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Doka.EntityFrameworkCore.MySql.RuntimeSmoke.CompiledModels.Spatial
{
    public partial class SpatialSmokeContextModel
    {
        private SpatialSmokeContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("56395a36-3f84-4f2d-b5d4-01dbe224b30e"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var spatialSmokeEntity = SpatialSmokeEntityEntityType.Create(this);

            SpatialSmokeEntityEntityType.CreateAnnotations(spatialSmokeEntity);

            AddAnnotation("ProductVersion", "10.0.4");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var spatialSmokeEntity = FindEntityType("Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+SpatialSmokeEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            spatialSmokeEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityTableBase = new TableBase("Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+SpatialSmokeEntity", null, relationalModel);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "int", dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityTableBase);
            dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityTableBase.Columns.Add("Id", idColumnBase);
            var locationColumnBase = new ColumnBase<ColumnMappingBase>("Location", "point", dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityTableBase);
            dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityTableBase.Columns.Add("Location", locationColumnBase);
            relationalModel.DefaultTables.Add("Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+SpatialSmokeEntity", dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityTableBase);
            var dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityMappingBase = new TableMappingBase<ColumnMappingBase>(spatialSmokeEntity, dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityTableBase, null);
            dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityTableBase.AddTypeMapping(dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityMappingBase, false);
            defaultTableMappings.Add(dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, spatialSmokeEntity.FindProperty("Id")!, dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)locationColumnBase, spatialSmokeEntity.FindProperty("Location")!, dokaEntityFrameworkCoreMySqlRuntimeSmokeProgramSpatialSmokeEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            spatialSmokeEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var spatialEntitiesTable = new Table("SpatialEntities", null, relationalModel);
            var idColumn = new Column("Id", "int", spatialEntitiesTable);
            spatialEntitiesTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            idColumn.AddAnnotation("Doka:MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.AutoIncrement);
            var locationColumn = new Column("Location", "point", spatialEntitiesTable);
            spatialEntitiesTable.Columns.Add("Location", locationColumn);
            locationColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Point>(locationColumn);
            locationColumn.AddAnnotation("Doka:MySql:SpatialReferenceSystemId", 4326);
            relationalModel.Tables.Add(("SpatialEntities", null), spatialEntitiesTable);
            var spatialEntitiesTableMapping = new TableMapping(spatialSmokeEntity, spatialEntitiesTable, null);
            spatialEntitiesTable.AddTypeMapping(spatialEntitiesTableMapping, false);
            tableMappings.Add(spatialEntitiesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, spatialSmokeEntity.FindProperty("Id")!, spatialEntitiesTableMapping);
            RelationalModel.CreateColumnMapping(locationColumn, spatialSmokeEntity.FindProperty("Location")!, spatialEntitiesTableMapping);
            var pK_SpatialEntities = new UniqueConstraint("PK_SpatialEntities", spatialEntitiesTable, new[] { idColumn });
            spatialEntitiesTable.PrimaryKey = pK_SpatialEntities;
            pK_SpatialEntities.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_SpatialEntities));
            var pK_SpatialEntitiesKey = RelationalModel.GetKey(this,
                "Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+SpatialSmokeEntity",
                new[] { "Id" });
            pK_SpatialEntities.MappedKeys.Add(pK_SpatialEntitiesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SpatialEntitiesKey).Add(pK_SpatialEntities);
            spatialEntitiesTable.UniqueConstraints.Add("PK_SpatialEntities", pK_SpatialEntities);
            var iX_SpatialEntities_Location = new TableIndex(
            "IX_SpatialEntities_Location", spatialEntitiesTable, new[] { locationColumn }, false);
            iX_SpatialEntities_Location.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Point>(iX_SpatialEntities_Location));
            var iX_SpatialEntities_LocationIx = RelationalModel.GetIndex(this,
                "Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+SpatialSmokeEntity",
                new[] { "Location" });
            iX_SpatialEntities_Location.MappedIndexes.Add(iX_SpatialEntities_LocationIx);
            RelationalModel.GetOrCreateTableIndexes(iX_SpatialEntities_LocationIx).Add(iX_SpatialEntities_Location);
            spatialEntitiesTable.Indexes.Add("IX_SpatialEntities_Location", iX_SpatialEntities_Location);
            return relationalModel.MakeReadOnly();
        }
    }
}
