// <auto-generated />
using Doka.EntityFrameworkCore.MySql.RuntimeSmoke;
using Doka.EntityFrameworkCore.MySql.RuntimeSmoke.CompiledModels.Spatial;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(Program.SpatialSmokeContext), typeof(SpatialSmokeContextModel))]
