// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using NetTopologySuite.Geometries;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Doka.EntityFrameworkCore.MySql.RuntimeSmoke.CompiledModels.Spatial
{
    [EntityFrameworkInternal]
    public partial class SpatialSmokeEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Doka.EntityFrameworkCore.MySql.RuntimeSmoke.Program+SpatialSmokeEntity",
                typeof(Program.SpatialSmokeEntity),
                baseEntityType,
                propertyCount: 2,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Program.SpatialSmokeEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Program.SpatialSmokeEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (Program.SpatialSmokeEntity instance) => SpatialSmokeEntityUnsafeAccessors.Id(instance),
                bool (Program.SpatialSmokeEntity instance) => SpatialSmokeEntityUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                Program.SpatialSmokeEntity (Program.SpatialSmokeEntity instance, int value) =>
                {
                    SpatialSmokeEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                Program.SpatialSmokeEntity (Program.SpatialSmokeEntity instance, int value) =>
                {
                    SpatialSmokeEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && SpatialSmokeEntityUnsafeAccessors.Id(((Program.SpatialSmokeEntity)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : SpatialSmokeEntityUnsafeAccessors.Id(((Program.SpatialSmokeEntity)(entry.Entity))))),
                int (IInternalEntry entry) => SpatialSmokeEntityUnsafeAccessors.Id(((Program.SpatialSmokeEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Doka:MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.AutoIncrement);

            var location = runtimeEntityType.AddProperty(
                "Location",
                typeof(Point),
                propertyInfo: typeof(Program.SpatialSmokeEntity).GetProperty("Location", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Program.SpatialSmokeEntity).GetField("<Location>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            location.SetGetter(
                Point (Program.SpatialSmokeEntity instance) => SpatialSmokeEntityUnsafeAccessors.Location(instance),
                bool (Program.SpatialSmokeEntity instance) => SpatialSmokeEntityUnsafeAccessors.Location(instance) == null);
            location.SetSetter(
                Program.SpatialSmokeEntity (Program.SpatialSmokeEntity instance, Point value) =>
                {
                    SpatialSmokeEntityUnsafeAccessors.Location(instance) = value;
                    return instance;
                });
            location.SetMaterializationSetter(
                Program.SpatialSmokeEntity (Program.SpatialSmokeEntity instance, Point value) =>
                {
                    SpatialSmokeEntityUnsafeAccessors.Location(instance) = value;
                    return instance;
                });
            location.SetAccessors(
                Point (IInternalEntry entry) => SpatialSmokeEntityUnsafeAccessors.Location(((Program.SpatialSmokeEntity)(entry.Entity))),
                Point (IInternalEntry entry) => SpatialSmokeEntityUnsafeAccessors.Location(((Program.SpatialSmokeEntity)(entry.Entity))),
                Point (IInternalEntry entry) => entry.ReadOriginalValue<Point>(location, 1),
                Point (IInternalEntry entry) => entry.GetCurrentValue<Point>(location));
            location.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            location.TypeMapping = null;
            location.AddAnnotation("Doka:MySql:SpatialReferenceSystemId", 4326);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { location });
            index.AddAnnotation("Doka:MySql:SpatialIndex", true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var location = runtimeEntityType.FindProperty("Location");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Program.SpatialSmokeEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, Point>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<Point>(location) == null ? null : ((ValueComparer<Point>)(((IProperty)location).GetValueComparer())).Snapshot(source.GetCurrentValue<Point>(location))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Program.SpatialSmokeEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 2,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 2,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "SpatialEntities");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
