// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using NetTopologySuite.Geometries;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Doka.EntityFrameworkCore.MySql.RuntimeSmoke.CompiledModels.Spatial
{
    public static class SpatialSmokeEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(Program.SpatialSmokeEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Location>k__BackingField")]
        public static extern ref Point Location(Program.SpatialSmokeEntity @this);
    }
}
