global using System;
global using System.Buffers.Binary;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Data;
global using System.Data.Common;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.IO.Compression;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Net.Sockets;
global using System.Runtime.InteropServices;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using BenchmarkDotNet.Reports;
global using Doka.EntityFrameworkCore.MySql.AdrValidator;
global using Doka.EntityFrameworkCore.MySql.TestUtilities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata;
global using Microsoft.EntityFrameworkCore.Migrations;
global using Microsoft.EntityFrameworkCore.Migrations.Operations;
global using Microsoft.EntityFrameworkCore.Query;
global using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.EntityFrameworkCore.ValueGeneration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using MySqlConnector;
global using NetTopologySuite.Geometries;
global using NetTopologySuite.IO;
global using Xunit;
global using BenchmarkPerformanceGate = Doka.EntityFrameworkCore.MySql.Benchmarks.PerformanceGate;
global using CoverageContract = Doka.EntityFrameworkCore.MySql.CoverageGate.CoverageContract;
global using DocumentationContract = Doka.EntityFrameworkCore.MySql.RepositoryContract.DocumentationContract;
global using EngineeringSurfaceContract = Doka.EntityFrameworkCore.MySql.RepositoryContract.EngineeringSurfaceContract;
global using ImagePinContract = Doka.EntityFrameworkCore.MySql.RepositoryContract.ImagePinContract;
global using NuGetSymbolReadbackManifestBuilder = Doka.EntityFrameworkCore.MySql.NuGetSymbolReadback.SymbolReadbackManifestBuilder;
global using RepositoryContractValidator = Doka.EntityFrameworkCore.MySql.RepositoryContract.RepositoryContractValidator;
