namespace Doka.EntityFrameworkCore.MySql.AdrValidator;

internal static class AdrIndexRenderer
{
    public const string ReadmeRelativePath = "docs/decisions/README.md";
    public const string JsonRelativePath = "docs/decisions/decision-index.json";

    /// <summary>
    /// Writes the human-readable index and machine-readable decision inventory.
    /// </summary>
    /// <param name="repositoryRoot">The absolute repository root.</param>
    /// <param name="documents">Validated ADRs in identifier order.</param>
    public static void WriteGeneratedArtifacts(
        string repositoryRoot,
        IReadOnlyList<AdrDocument> documents
    )
    {
        var utf8WithoutBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
        File.WriteAllText(Path.Combine(repositoryRoot, ReadmeRelativePath), RenderReadme(documents), utf8WithoutBom);
        File.WriteAllText(Path.Combine(repositoryRoot, JsonRelativePath), RenderJson(documents), utf8WithoutBom);
    }

    /// <summary>
    /// Renders the canonical decision table and relationship graph.
    /// </summary>
    /// <param name="documents">Validated ADRs in identifier order.</param>
    /// <returns>The deterministic Markdown index.</returns>
    public static string RenderReadme(
        IReadOnlyList<AdrDocument> documents
    )
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Architecture Decision Records");
        builder.AppendLine();
        builder.AppendLine("This index is generated by `eng/validate-adrs.sh --write-index` from the");
        builder.AppendLine("validated ADR metadata. Manual edits are rejected by the governance gate.");
        builder.AppendLine();
        builder.AppendLine("## Decision Index");
        builder.AppendLine();
        builder.AppendLine("| ID | Status | Date | Decision | Relationships |");
        builder.AppendLine("|---|---|---|---|---|");

        foreach (var document in documents)
        {
            builder
                .Append("| [")
                .Append(document.Id)
                .Append("](")
                .Append(Path.GetFileName(document.RelativePath))
                .Append(") | ")
                .Append(document.Status)
                .Append(" | ")
                .Append(document.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture))
                .Append(" | ")
                .Append(EscapeTableCell(document.Title))
                .Append(" | ")
                .Append(RenderRelationships(document))
                .AppendLine(" |");
        }

        builder.AppendLine();
        builder.AppendLine("## Relationship Graph");
        builder.AppendLine();
        builder.AppendLine("```mermaid");
        builder.AppendLine("flowchart LR");

        var relationships = documents
            .SelectMany(document => document
                .Supersedes.Select(target => (document.Id, Verb: "supersedes", Target: target))
                .Concat(document.Amends.Select(target => (document.Id, Verb: "amends", Target: target))))
            .OrderBy(static relationship => relationship.Id, StringComparer.Ordinal)
            .ThenBy(static relationship => relationship.Verb, StringComparer.Ordinal)
            .ThenBy(static relationship => relationship.Target, StringComparer.Ordinal)
            .ToArray();

        if (relationships.Length == 0)
        {
            builder.AppendLine("  NONE[\"No decision relationships recorded\"]");
        }
        else
        {
            foreach (var relationship in relationships)
            {
                builder
                    .Append("  ")
                    .Append(ToMermaidId(relationship.Id))
                    .Append("[\"")
                    .Append(relationship.Id)
                    .Append("\"] -->|\"")
                    .Append(relationship.Verb)
                    .Append("\"| ")
                    .Append(ToMermaidId(relationship.Target))
                    .Append("[\"")
                    .Append(relationship.Target)
                    .AppendLine("\"]");
            }
        }

        builder.AppendLine("```");
        return builder.ToString();
    }

    /// <summary>
    /// Renders the canonical machine-readable decision inventory.
    /// </summary>
    /// <param name="documents">Validated ADRs in identifier order.</param>
    /// <returns>The deterministic JSON document.</returns>
    public static string RenderJson(
        IReadOnlyList<AdrDocument> documents
    )
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(
                   stream,
                   new JsonWriterOptions
                   {
                       Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
                       Indented = true
                   }))
        {
            writer.WriteStartObject();
            writer.WriteNumber("schemaVersion", 1);
            writer.WriteString("madrVersion", "4.0.0");
            writer.WriteString("dokaProfileVersion", "1.0");
            writer.WriteStartArray("decisions");

            foreach (var document in documents)
            {
                writer.WriteStartObject();
                writer.WriteString("id", document.Id);
                writer.WriteString("title", document.Title);
                writer.WriteString("status", document.Status);
                writer.WriteString("date", document.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
                writer.WriteString("path", document.RelativePath);
                WriteArray(writer, "supersedes", document.Supersedes);
                WriteArray(writer, "supersededBy", document.SupersededBy);
                WriteArray(writer, "amends", document.Amends);
                WriteArray(writer, "amendedBy", document.AmendedBy);
                writer.WriteEndObject();
            }

            writer.WriteEndArray();
            writer.WriteEndObject();
        }

        return Encoding.UTF8.GetString(stream.ToArray()) + Environment.NewLine;
    }

    private static void WriteArray(
        Utf8JsonWriter writer,
        string propertyName,
        IReadOnlyList<string> values
    )
    {
        writer.WriteStartArray(propertyName);
        foreach (var value in values)
        {
            writer.WriteStringValue(value);
        }

        writer.WriteEndArray();
    }

    private static string RenderRelationships(
        AdrDocument document
    )
    {
        var entries = new List<string>();
        AddRelationships(entries, "supersedes", document.Supersedes);
        AddRelationships(entries, "superseded by", document.SupersededBy);
        AddRelationships(entries, "amends", document.Amends);
        AddRelationships(entries, "amended by", document.AmendedBy);
        return entries.Count == 0 ? "-" : string.Join("; ", entries);
    }

    private static void AddRelationships(
        List<string> entries,
        string label,
        IReadOnlyList<string> targets
    )
    {
        if (targets.Count > 0)
        {
            entries.Add($"{label} {string.Join(", ", targets)}");
        }
    }

    private static string EscapeTableCell(
        string value
    ) => value.Replace("|", "\\|", StringComparison.Ordinal);

    private static string ToMermaidId(
        string value
    ) => value.Replace("-", "_", StringComparison.Ordinal);
}
